=== edwardhendrawan/WSassignment/WebContent/WEB-INF/polls.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" targetNamespace="assign1" xmlns:xs="http://www.w3.org/2001/XMLSchema">
   
  
  <xs:element name="polls">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="poll" maxOccurs="unbounded" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:string" name="title"/>
              <xs:element type="xs:int" name="state"/>
              <xs:element type="xs:int" name="userID"/>
              <xs:element type="xs:string" name="datecreated"/>
              <xs:element type="xs:string" name="location"/>
              <xs:element type="xs:string" name="description"/>
              <xs:element name="meetings">
                <xs:complexType mixed="true">
                  <xs:sequence>
                    <xs:element name="meeting" maxOccurs="unbounded" minOccurs="1">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element type="xs:string" name="time"/>
                          <xs:element type="xs:string" name="date"/>
                          <xs:element name="responses">
                            <xs:complexType mixed="true">
                              <xs:sequence>
                                <xs:element type="xs:string" name="response" maxOccurs="unbounded" minOccurs="0"/>
                              </xs:sequence>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                        <xs:attribute type="xs:int" name="option" use="optional"/>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute type="xs:int" name="id" use="optional"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== edwardhendrawan/WSassignment/WebContent/WEB-INF/polls.xml
<?xml version="1.0" encoding="UTF-8" ?>
<polls xmlns="uts.wsd.assign1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="polls.xsd">
	<poll id="1">
		<title>WSD Meeting</title>
		<state>Open</state>
		<name>Ryan Heise</name>
		<datecreated>88/88/1996</datecreated>
		<location>UTS</location>
		<description>Meeting for assignment</description>
		<meetings>
			<meeting>
				<time>12:00</time>
				<date>99/88/1996</date>
				<responses>
					<response avail="yes">John Doe</response>
					<response avail="no">John Smith</response>
				</responses>
			</meeting>
			<meeting>
				<time>12:00</time>
				<date>99/88/1996</date>
				<responses>
					<response avail="yes">John Doe</response>
					<response avail="no">John Smith</response>
				</responses>
			</meeting>
		</meetings>
	</poll>
	<poll id="2">
		<state>Closed</state>
		<title>WSD Meeting</title>
		<name>Ryan Heise</name>
		<datecreated>88/88/1996</datecreated>
		<location>UTS</location>
		<description>Meeting for assignment</description>
		<meetings>
			<meeting>
				<time>12:00</time>
				<date>99/88/1996</date>
				<responses>
					<response avail="yes">John Doe</response>
					<response avail="no">John Smith</response>
				</responses>
			</meeting>
			<meeting>
				<time>12:00</time>
				<date>99/88/1996</date>
				<responses>
					<response avail="yes">John Doe</response>
					<response avail="no">John Smith</response>
				</responses>
			</meeting>
		</meetings>
	</poll>
</polls>
